trigger:
- feature/wip

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    displayName: Deploy Solution
    jobs:
      - template: template-deploy.yml
        parameters:
          parameters:
          azureServiceConnection: K-Talk-Subscription
          resourceGroupName: RG-KTALK-DFDEVOPS-DEV