trigger:
- feature/wip

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    displayName: Deploy Solution
    jobs:
      - template: template-deploy.yml
        parameters:
          azureServiceConnection: KTalkSubscription
          environmentName: Development