trigger:
- feature/wip

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build K-Talk Solution
    jobs:
      - template: template-build.yml

  - stage: Deploy
    displayName: Deploy K-Talk Solution
    jobs:
      - template: template-deploy.yml
        parameters:
          azureServiceConnection: KTalkSubscription
          environmentName: Development