parameters:
- name: azureServiceConnection
  displayName: Azure Service Connection?
  type: string
- name: environmentName
  displayName: Azure EnvironmentName?
  type: string
- name: deployInfrastructure
  displayName: Should Deploy Infrastructure?
  type: boolean
  default: true

jobs:
- job: DeployInfrastructure
  displayName: Deploy Infrastructure
  variables:
    - group: 'ktalk-${{ parameters.environmentName }}-settings'
  pool:
    vmImage: ubuntu-latest
  steps:
    # Deploy Infrastructure
    - task: AzureCLI@2
      condition: and(succeeded(), eq('${{ parameters.deployInfrastructure }}', 'true'))
      displayName: Deploy Infrastructure to $(AzureResourceGroupName)
      inputs:
        azureSubscription: $(AzureServiceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az group create --name $(AzureResourceGroupName) --location $(AzureResourceGroupLocation)
          az deployment group create --resource-group $(AzureResourceGroupName) --template-file $(System.DefaultWorkingDirectory)/azure/main.bicep