parameters:
- name: azureServiceConnection
  displayName: Azure Service Connection?
  type: string
- name: environmentName
  displayName: Azure EnvironmentName?
  type: string
- name: deployInfrastructure
  displayName: Should Deploy Infrastructure?
  type: boolean
  default: true

jobs:
- deployment: Deploy
  displayName: Deploy to ${{ parameters.environmentName }} Environment
  variables:
    - group: 'ktalk-${{ parameters.environmentName }}-settings'
  pool:
    vmImage: ubuntu-latest
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
          # Deploy Infrastructure
          - task: AzureCLI@2
            condition: and(succeeded(), eq('${{ parameters.deployInfrastructure }}', 'true'))
            displayName: Deploy Infrastructure
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az group create --name $(AzureResourceGroupName) --location $(AzureResourceGroupLocation)
                az deployment group create --resource-group $(AzureResourceGroupName) --template-file $(Pipeline.Workspace)/azure/main.bicep