parameters:
- name: azureServiceConnection
  displayName: Azure Service Connection?
  type: string
- name: resourceGroupName
  displayName: Azure Resource Group?
  type: string
- name: deployInfrastructure
  displayName: Should Deploy Infrastructure?
  type: boolean
  default: true
- name: resourceGroupNameLocation
  displayName: Azure Resource Group Location?
  type: string
  default: australiasoutheast

jobs:
- job: DeployInfrastructure
  displayName: Deploy Infrastructure
  variables:
    vmImageName: 'ubuntu-latest'
    templateFile: '$(System.DefaultWorkingDirectory)/azure/main.bicep'
  pool:
    vmImage: $(vmImageName)
  steps:
    # Build
    - task: AzureCLI@2
      condition: and(succeeded(), eq('${{ parameters.deployInfrastructure }}', 'true'))
      displayName: Deploy Infrastructure to ${{ parameters.resourceGroupName }}
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.resourceGroupNameLocation }}
          az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file $(templateFile)